/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuizzesIndexRouteImport } from './routes/quizzes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as LeaderboardIndexRouteImport } from './routes/leaderboard/index'
import { Route as QuizzesResultsRouteImport } from './routes/quizzes/results'
import { Route as QuizzesQuizIdRouteImport } from './routes/quizzes/$quizId'
import { Route as LoginSignupRouteImport } from './routes/login/signup'

const QuizzesIndexRoute = QuizzesIndexRouteImport.update({
  id: '/quizzes/',
  path: '/quizzes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardIndexRoute = LeaderboardIndexRouteImport.update({
  id: '/leaderboard/',
  path: '/leaderboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizzesResultsRoute = QuizzesResultsRouteImport.update({
  id: '/quizzes/results',
  path: '/quizzes/results',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizzesQuizIdRoute = QuizzesQuizIdRouteImport.update({
  id: '/quizzes/$quizId',
  path: '/quizzes/$quizId',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginSignupRoute = LoginSignupRouteImport.update({
  id: '/login/signup',
  path: '/login/signup',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/login/signup': typeof LoginSignupRoute
  '/quizzes/$quizId': typeof QuizzesQuizIdRoute
  '/quizzes/results': typeof QuizzesResultsRoute
  '/leaderboard': typeof LeaderboardIndexRoute
  '/login': typeof LoginIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/quizzes': typeof QuizzesIndexRoute
}
export interface FileRoutesByTo {
  '/login/signup': typeof LoginSignupRoute
  '/quizzes/$quizId': typeof QuizzesQuizIdRoute
  '/quizzes/results': typeof QuizzesResultsRoute
  '/leaderboard': typeof LeaderboardIndexRoute
  '/login': typeof LoginIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/quizzes': typeof QuizzesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/login/signup': typeof LoginSignupRoute
  '/quizzes/$quizId': typeof QuizzesQuizIdRoute
  '/quizzes/results': typeof QuizzesResultsRoute
  '/leaderboard/': typeof LeaderboardIndexRoute
  '/login/': typeof LoginIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/quizzes/': typeof QuizzesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login/signup'
    | '/quizzes/$quizId'
    | '/quizzes/results'
    | '/leaderboard'
    | '/login'
    | '/profile'
    | '/quizzes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login/signup'
    | '/quizzes/$quizId'
    | '/quizzes/results'
    | '/leaderboard'
    | '/login'
    | '/profile'
    | '/quizzes'
  id:
    | '__root__'
    | '/login/signup'
    | '/quizzes/$quizId'
    | '/quizzes/results'
    | '/leaderboard/'
    | '/login/'
    | '/profile/'
    | '/quizzes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LoginSignupRoute: typeof LoginSignupRoute
  QuizzesQuizIdRoute: typeof QuizzesQuizIdRoute
  QuizzesResultsRoute: typeof QuizzesResultsRoute
  LeaderboardIndexRoute: typeof LeaderboardIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  QuizzesIndexRoute: typeof QuizzesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quizzes/': {
      id: '/quizzes/'
      path: '/quizzes'
      fullPath: '/quizzes'
      preLoaderRoute: typeof QuizzesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard/': {
      id: '/leaderboard/'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quizzes/results': {
      id: '/quizzes/results'
      path: '/quizzes/results'
      fullPath: '/quizzes/results'
      preLoaderRoute: typeof QuizzesResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quizzes/$quizId': {
      id: '/quizzes/$quizId'
      path: '/quizzes/$quizId'
      fullPath: '/quizzes/$quizId'
      preLoaderRoute: typeof QuizzesQuizIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/signup': {
      id: '/login/signup'
      path: '/login/signup'
      fullPath: '/login/signup'
      preLoaderRoute: typeof LoginSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  LoginSignupRoute: LoginSignupRoute,
  QuizzesQuizIdRoute: QuizzesQuizIdRoute,
  QuizzesResultsRoute: QuizzesResultsRoute,
  LeaderboardIndexRoute: LeaderboardIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  QuizzesIndexRoute: QuizzesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
